version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      kafka_net:

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      kafka_net:

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      kafka_net:

  kafka1:
    build: kafka-src/
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.28.0.2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKER_ID: 1
    networks:
      kafka_net:
        ipv4_address: 172.28.0.2

  kafka2:
    build: kafka-src/
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.28.0.3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKER_ID: 2
    networks:
      kafka_net:
        ipv4_address: 172.28.0.3

  kafka3:
    build: kafka-src/
    ports:
      - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.28.0.4
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKER_ID: 3
    networks:
      kafka_net:
        ipv4_address: 172.28.0.4

networks:
  kafka_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.28.0.0/16
