version: '3.1'

services:
  zookeeper:
    image: zookeeper
    restart: always
    container_name: local-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ./zookeeper-logs/data:/data
      - ./zookeeper-logs/datalog:/datalog

  kafka:
    image: wurstmeister/kafka
    restart: always
    container_name: local-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "cat:1:1,test:1:1"
      KAFKA_LOG_DIRS: "/kafka"
    depends_on:
      - zookeeper
    volumes:
      - ./kafka-logs:/kafka
